// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/function.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_proto_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temp          string                 `protobuf:"bytes,1,opt,name=Temp,proto3" json:"Temp,omitempty"`
	FeelsLike     string                 `protobuf:"bytes,2,opt,name=FeelsLike,proto3" json:"FeelsLike,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
	Wind360       string                 `protobuf:"bytes,5,opt,name=Wind360,proto3" json:"Wind360,omitempty"`
	WindDir       string                 `protobuf:"bytes,6,opt,name=WindDir,proto3" json:"WindDir,omitempty"`
	WindScale     string                 `protobuf:"bytes,7,opt,name=WindScale,proto3" json:"WindScale,omitempty"`
	WindSpeed     string                 `protobuf:"bytes,8,opt,name=WindSpeed,proto3" json:"WindSpeed,omitempty"`
	Humidity      string                 `protobuf:"bytes,9,opt,name=Humidity,proto3" json:"Humidity,omitempty"`
	Precip        string                 `protobuf:"bytes,10,opt,name=Precip,proto3" json:"Precip,omitempty"`
	Pressure      string                 `protobuf:"bytes,11,opt,name=Pressure,proto3" json:"Pressure,omitempty"`
	Vis           string                 `protobuf:"bytes,12,opt,name=Vis,proto3" json:"Vis,omitempty"`
	Cloud         string                 `protobuf:"bytes,13,opt,name=Cloud,proto3" json:"Cloud,omitempty"`
	Dew           string                 `protobuf:"bytes,14,opt,name=Dew,proto3" json:"Dew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_proto_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetTemp() string {
	if x != nil {
		return x.Temp
	}
	return ""
}

func (x *GetWeatherResponse) GetFeelsLike() string {
	if x != nil {
		return x.FeelsLike
	}
	return ""
}

func (x *GetWeatherResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetWeatherResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetWeatherResponse) GetWind360() string {
	if x != nil {
		return x.Wind360
	}
	return ""
}

func (x *GetWeatherResponse) GetWindDir() string {
	if x != nil {
		return x.WindDir
	}
	return ""
}

func (x *GetWeatherResponse) GetWindScale() string {
	if x != nil {
		return x.WindScale
	}
	return ""
}

func (x *GetWeatherResponse) GetWindSpeed() string {
	if x != nil {
		return x.WindSpeed
	}
	return ""
}

func (x *GetWeatherResponse) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

func (x *GetWeatherResponse) GetPrecip() string {
	if x != nil {
		return x.Precip
	}
	return ""
}

func (x *GetWeatherResponse) GetPressure() string {
	if x != nil {
		return x.Pressure
	}
	return ""
}

func (x *GetWeatherResponse) GetVis() string {
	if x != nil {
		return x.Vis
	}
	return ""
}

func (x *GetWeatherResponse) GetCloud() string {
	if x != nil {
		return x.Cloud
	}
	return ""
}

func (x *GetWeatherResponse) GetDew() string {
	if x != nil {
		return x.Dew
	}
	return ""
}

type GetWeatherReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherReportRequest) Reset() {
	*x = GetWeatherReportRequest{}
	mi := &file_proto_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReportRequest) ProtoMessage() {}

func (x *GetWeatherReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReportRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeatherReportRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetWeatherReportRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type GetWeatherReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        string                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherReportResponse) Reset() {
	*x = GetWeatherReportResponse{}
	mi := &file_proto_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherReportResponse) ProtoMessage() {}

func (x *GetWeatherReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherReportResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_function_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeatherReportResponse) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

var File_proto_function_proto protoreflect.FileDescriptor

const file_proto_function_proto_rawDesc = "" +
	"\n" +
	"\x14proto/function.proto\x12\bfunction\"/\n" +
	"\x11GetWeatherRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"\xe8\x02\n" +
	"\x12GetWeatherResponse\x12\x12\n" +
	"\x04Temp\x18\x01 \x01(\tR\x04Temp\x12\x1c\n" +
	"\tFeelsLike\x18\x02 \x01(\tR\tFeelsLike\x12\x12\n" +
	"\x04Icon\x18\x03 \x01(\tR\x04Icon\x12\x12\n" +
	"\x04Text\x18\x04 \x01(\tR\x04Text\x12\x18\n" +
	"\aWind360\x18\x05 \x01(\tR\aWind360\x12\x18\n" +
	"\aWindDir\x18\x06 \x01(\tR\aWindDir\x12\x1c\n" +
	"\tWindScale\x18\a \x01(\tR\tWindScale\x12\x1c\n" +
	"\tWindSpeed\x18\b \x01(\tR\tWindSpeed\x12\x1a\n" +
	"\bHumidity\x18\t \x01(\tR\bHumidity\x12\x16\n" +
	"\x06Precip\x18\n" +
	" \x01(\tR\x06Precip\x12\x1a\n" +
	"\bPressure\x18\v \x01(\tR\bPressure\x12\x10\n" +
	"\x03Vis\x18\f \x01(\tR\x03Vis\x12\x14\n" +
	"\x05Cloud\x18\r \x01(\tR\x05Cloud\x12\x10\n" +
	"\x03Dew\x18\x0e \x01(\tR\x03Dew\"I\n" +
	"\x17GetWeatherReportRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"2\n" +
	"\x18GetWeatherReportResponse\x12\x16\n" +
	"\x06report\x18\x01 \x01(\tR\x06report2\xb9\x01\n" +
	"\x0fFunctionService\x12I\n" +
	"\n" +
	"GetWeather\x12\x1b.function.GetWeatherRequest\x1a\x1c.function.GetWeatherResponse\"\x00\x12[\n" +
	"\x10GetWeatherReport\x12!.function.GetWeatherReportRequest\x1a\".function.GetWeatherReportResponse\"\x00B?Z=github.com/mathiasXie/gin-web/applications/function-rpc/protob\x06proto3"

var (
	file_proto_function_proto_rawDescOnce sync.Once
	file_proto_function_proto_rawDescData []byte
)

func file_proto_function_proto_rawDescGZIP() []byte {
	file_proto_function_proto_rawDescOnce.Do(func() {
		file_proto_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_function_proto_rawDesc), len(file_proto_function_proto_rawDesc)))
	})
	return file_proto_function_proto_rawDescData
}

var file_proto_function_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_function_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),        // 0: function.GetWeatherRequest
	(*GetWeatherResponse)(nil),       // 1: function.GetWeatherResponse
	(*GetWeatherReportRequest)(nil),  // 2: function.GetWeatherReportRequest
	(*GetWeatherReportResponse)(nil), // 3: function.GetWeatherReportResponse
}
var file_proto_function_proto_depIdxs = []int32{
	0, // 0: function.FunctionService.GetWeather:input_type -> function.GetWeatherRequest
	2, // 1: function.FunctionService.GetWeatherReport:input_type -> function.GetWeatherReportRequest
	1, // 2: function.FunctionService.GetWeather:output_type -> function.GetWeatherResponse
	3, // 3: function.FunctionService.GetWeatherReport:output_type -> function.GetWeatherReportResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_function_proto_init() }
func file_proto_function_proto_init() {
	if File_proto_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_function_proto_rawDesc), len(file_proto_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_function_proto_goTypes,
		DependencyIndexes: file_proto_function_proto_depIdxs,
		MessageInfos:      file_proto_function_proto_msgTypes,
	}.Build()
	File_proto_function_proto = out.File
	file_proto_function_proto_goTypes = nil
	file_proto_function_proto_depIdxs = nil
}
